### PR TITLE
Fix #138: Fixing CSV export

### LINKED ISSUE #138: exports werken niet
"./app/console intracto:exportmails" werkt niet omwille van allerhande problemen:
- directory rechten (mysql user heeft geen schrijf rechten op onze documentroot)
- mysql --secure-file-priv (mag niet eens files schrijven in die direcotry)
- sql_mode=only_full_group_by (velden van select zitten niet in group by, query klopt niet)

dat moet iemand nakijken en fixen. Best gewoon data binnenhalen en dan via php naar file schrijven? Graag ook testen in productie

ik heb dit _nu_ nodig en het werkt niet ...

### PR DESCRIPTION
**Pull request by mvanspringel**
CSV files are now generated by PHP instead of mysql and are saved to /tmp instead of /export. See #138

### CODE REVIEW

File: src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php [hunk 1]
```diff
@@ -334,24 +334,37 @@ public function calculateAverageEntriesPerPool(Season $season)
...
+            GROUP BY e.name, e.email, e.poolId",
             [
                 'firstDay' => $season->getStart()->format('Y-m-d H:i:s'),
-                'lastDay' => $season->getEnd()->format('Y-m-d H:i:s'),
-                'location' => '/tmp/'.date('Y-m-d H.i.s').'_admins.csv',
+                'lastDay' => $season->getEnd()->format('Y-m-d H:i:s')
             ]
         );
+
+        // Add the data queried from database
```
Comment (tvlooy) [inline src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php]: @mvanspringel zo'n comments brengen weinig meerwaarde, zijn "noise comments" verwijderd in 08d1b954e172c808a4bdcc38b160347535667801
